In [10]:
# 01_time_domain_basics.ipynb
# manual convolution
import numpy as np
# Take input as a string, split by space, and convert each element to an integer
x_input = list(map(int, input("Enter elements separated by space: ").split()))
h_input = list(map(int, input("Enter elements separated by space: ").split()))
# Convert the list to a NumPy array
x = np.array(x_input)
h = np.array(h_input)

# Length of the output signal
N = len(x) + len(h) - 1
y = np.zeros(N)
for n in range(N):
    for k in range(len(x)):
        if (0 <= n-k < len(h)):
            y[n] += x[k] * h[n-k]
        else: 
            y[n] += 0
print("Output signal y[n]:", y)

Output signal y[n]: [ 1.  3.  6. 10.  9.  7.  4.]


In [ ]:
# using numpy's built-in convolution function
import numpy as np
# Take input as a string, split by space, and convert each element to an integer
x_input = list(map(int, input("Enter elements separated by space: ").split()))
h_input = list(map(int, input("Enter elements separated by space: ").split()))
# Convert the list to a NumPy array
x = np.array(x_input)
h = np.array(h_input)
y = np.convolve(x, h)
print("Output signal y[n]:", y)

Output signal y[n]: [ 1  3  6 10  9  7  4]


In [ ]:
# checking commutativity of convolution
import numpy as np
# Take input as a string, split by space, and convert each element to an integer
x_input = list(map(int, input("Enter elements separated by space: ").split()))
h_input = list(map(int, input("Enter elements separated by space: ").split()))
# Convert the list to a NumPy array
x = np.array(x_input)
h = np.array(h_input)
y1 = np.convolve(x, h)
print("Output signal y1[n]:", y1)
y2 = np.convolve(h,x)
print("Output signal y2[n]:", y2)
if np.array_equal(y1, y2):
    print("The convolution is commutative: y1[n] = y2[n]")
else:    print("The convolution is not commutative: y1[n] != y2[n]")

Output signal y1[n]: [ 1  3  6 10  9  7  4]
Output signal y2[n]: [ 1  3  6 10  9  7  4]
The convolution is commutative: y1[n] = y2[n]


In [5]:
# convolution with delta function
import numpy as np
# Take input as a string, split by space, and convert each element to an integer
x_input = list(map(int, input("Enter elements separated by space: ").split()))
# Create a delta function (impulse signal)
delta = np.zeros(len(x_input))
delta[0] = 1  # Set the first element to 1 (impulse at n=0)
# Convert the list to a NumPy array
x = np.array(x_input)
y = np.convolve(x, delta)
print("Output signal y[n]:", y)

#shifting using delta function
shift = int(input("Enter the shift value (positive for right shift, negative for left shift): "))
delta_shifted = np.roll(delta, shift)  # Shift the delta function
y_shifted = np.convolve(x, delta_shifted)
print("Output signal y[n] after shifting:", y_shifted)

Output signal y[n]: [1. 2. 3. 4. 0. 0. 0.]
Output signal y[n] after shifting: [0. 0. 0. 1. 2. 3. 4.]


In [10]:
#Toeplitz matrix for convolution
import numpy as np
# Take input as a string, split by space, and convert each element to an integer
x_input = list(map(int, input("Enter elements separated by space: ").split()))
h_input = list(map(int, input("Enter elements separated by space: ").split()))
# Convert the list to a NumPy array
x = np.array(x_input)
h = np.array(h_input)
# Create a Toeplitz matrix for convolution
N = len(x) + len(h) - 1
offset = len(h)//2
toeplitz_matrix = np.zeros((len(h), len(h)))
for i in range(len(h)):
    for j in range(len(h)):
        idx = i - j + offset
        if 0 <= idx < len(h):
            toeplitz_matrix[i,j] = h[idx]
print ("Toeplitz matrix for convolution:\n", toeplitz_matrix)
y = toeplitz_matrix @ x
print("Output signal y[n]:", y)

Toeplitz matrix for convolution:
 [[3. 2. 1. 0.]
 [4. 3. 2. 1.]
 [0. 4. 3. 2.]
 [0. 0. 4. 3.]]
Output signal y[n]: [ 6. 10.  9.  7.]
