In [ ]:
# logistic regression
import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

Prob: [0.96498425 0.03501575] Pred: 0 Actual: 0
Prob: [1.000000e+00 3.619588e-11] Pred: 0 Actual: 0
Prob: [9.99445882e-01 5.54118132e-04] Pred: 0 Actual: 0
Prob: [9.99999990e-01 9.75797269e-09] Pred: 0 Actual: 0
Prob: [9.99981767e-01 1.82334163e-05] Pred: 0 Actual: 0
Accuracy: 0.9765
Confusion Matrix:
 [[1136   23]
 [  24  817]]
Hours Studied : 4.864797320226543
Previous Scores : 11.613322689791433
Extracurricular Activities : 0.32166867055687987
Sleep Hours : 0.5133318297160231
Sample Question Papers Practiced : 0.41306591710192536


In [9]:
# logistic regression with threshold tuning
import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

y_pred_custom = (y_prob >= 0.8).astype(int)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred_custom[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_custom))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_custom))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

Prob: 0.03501574527650247 Pred: 0 Actual: 0
Prob: 3.619587997164217e-11 Pred: 0 Actual: 0
Prob: 0.0005541181323853268 Pred: 0 Actual: 0
Prob: 9.757972688411458e-09 Pred: 0 Actual: 0
Prob: 1.823341629722133e-05 Pred: 0 Actual: 0
Accuracy: 0.963
Confusion Matrix:
 [[1155    4]
 [  70  771]]
Hours Studied : 4.864797320226543
Previous Scores : 11.613322689791433
Extracurricular Activities : 0.32166867055687987
Sleep Hours : 0.5133318297160231
Sample Question Papers Practiced : 0.41306591710192536


In [ ]:
# logistic regression changing lambda for L2 regularization
import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(C = 0.01)
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

# observations:
# extremely small weights due to strong regularization when C = 0.01
# accuracy may decrease due to underfitting with strong regularization

Prob: [0.70931656 0.29068344] Pred: 0 Actual: 0
Prob: [0.99805745 0.00194255] Pred: 0 Actual: 0
Prob: [0.89865429 0.10134571] Pred: 0 Actual: 0
Prob: [0.99364022 0.00635978] Pred: 0 Actual: 0
Prob: [0.95345868 0.04654132] Pred: 0 Actual: 0
Accuracy: 0.9725
Confusion Matrix:
 [[1137   22]
 [  33  808]]
Hours Studied : 1.1263679538770737
Previous Scores : 3.1042556780965267
Extracurricular Activities : 0.06268531641705598
Sleep Hours : 0.12061817949648534
Sample Question Papers Practiced : 0.10879844031975734


In [21]:
# logistic regression with Cross-validation
import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class"], axis=1)
y = df["Performance Class"]

# creating pipelines
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

pipeline = make_pipeline(StandardScaler(), LogisticRegression())

scores = cross_val_score(pipeline, X, y, cv=5)

print("Cross-validation scores:", scores)
print("Mean CV accuracy:", scores.mean())

Cross-validation scores: [0.971  0.97   0.9785 0.9775 0.9735]
Mean CV accuracy: 0.9741
