In [ ]:
# feature engineering with Non-linear features

import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Non-linear features
df["sleep_squared"] = df["Sleep Hours"] ** 2

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class", "Sleep Hours"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

# Observations:
# - Adding hours² did not improve performance, suggesting that a simple linear relationship already captures most of the effect OR the added feature introduced noise/redundancy.
# - But on squaring sleep, there was an increase in accuracy to 98%.The improvement suggests a potential non-linear relationship between sleep and performance, where extremely low or high sleep may affect outcomes differently.

Prob: [0.9656195 0.0343805] Pred: 0 Actual: 0
Prob: [1.00000000e+00 4.03660346e-11] Pred: 0 Actual: 0
Prob: [9.99480457e-01 5.19542602e-04] Pred: 0 Actual: 0
Prob: [9.9999999e-01 9.6491261e-09] Pred: 0 Actual: 0
Prob: [9.99979997e-01 2.00025739e-05] Pred: 0 Actual: 0
Accuracy: 0.978
Confusion Matrix:
 [[1139   20]
 [  24  817]]
Hours Studied : 4.85590657631379
Previous Scores : 11.602994980708093
Extracurricular Activities : 0.3192752221319588
Sample Question Papers Practiced : 0.41295540772616424
sleep_squared : 0.509598460368635


In [ ]:
# feature engineering with interaction features

import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Interaction features
df["hours_prevscores_interaction"] = df["Hours Studied"] * df["Previous Scores"]

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class", "Hours Studied", "Previous Scores"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

# Observations:
# - Interaction features between hours studied and sleep hours reduced accuracy to 96%, suggesting that the interaction feature did not help, likely because the original features already captured the relationship sufficiently, or the interaction introduced unnecessary complexity.
# - Interaction between hours studied and previous scores reduced accuracy significantly to 74%, indicating that the linear effect of these features is more important for predicting performance.
# The interaction feature may have introduced strong multicollinearity or distorted the feature space, making it harder for the model to learn a stable decision boundary.



Prob: [0.59365592 0.40634408] Pred: 0 Actual: 0
Prob: [0.89566199 0.10433801] Pred: 0 Actual: 0
Prob: [0.4808079 0.5191921] Pred: 1 Actual: 0
Prob: [0.71013114 0.28986886] Pred: 0 Actual: 0
Prob: [0.56454498 0.43545502] Pred: 0 Actual: 0
Accuracy: 0.742
Confusion Matrix:
 [[930 229]
 [287 554]]
Extracurricular Activities : 0.04130690179290766
Sleep Hours : 0.07159735021175592
Sample Question Papers Practiced : 0.07123940464466427
hours_prevscores_interaction : 1.4817816253395912


In [ ]:
# feature engineering with ratio features

import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Ratio features
df["sleep_efficiency"] = df["Sleep Hours"] / (df["Hours Studied"] + 1)

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class", "Hours Studied", "Sleep Hours"], axis=1)
y = df["Performance Class"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the logistic regression model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

for i in range(5):
    print("Prob:", y_prob[i], "Pred:", y_pred[i], "Actual:", y_test.values[i])

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

for feature, weight in zip(X.columns, model.coef_[0]):
    print(feature, ":", weight)

# Observations:
# - Ratio features between hours studied and previous scores reduced accuracy to 57.2%, it likely destroys important independent information from both features, collapsing them into a single value and reducing predictive power.
# - Ratio between hours studied and sleep hours reduced accuracy to 93.25%, The ratio captures some relationship but loses individual feature contributions, leading to slightly worse performance than using them separately.


Prob: [0.84567475 0.15432525] Pred: 0 Actual: 0
Prob: [9.99855379e-01 1.44620864e-04] Pred: 0 Actual: 0
Prob: [0.99206743 0.00793257] Pred: 0 Actual: 0
Prob: [9.99958363e-01 4.16369919e-05] Pred: 0 Actual: 0
Prob: [0.99454091 0.00545909] Pred: 0 Actual: 0
Accuracy: 0.9325
Confusion Matrix:
 [[1087   72]
 [  63  778]]
Previous Scores : 5.881204220835451
Extracurricular Activities : 0.07832779350563171
Sample Question Papers Practiced : 0.23979056312142505
sleep_efficiency : -1.7602217257501416


In [8]:
# feature engineering with squared sleep feature and cross validation

import pandas as pd
import numpy as np

df = pd.read_csv("Student_Performance.csv")
df["Performance Class"] = (df["Performance Index"] >= 60).astype(int)

# Encoding Categorical Variables
# Convert categorical variables (Extra-curricular activities feature) to numeric variables (0/1)
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Non-linear features
df["sleep_squared"] = df["Sleep Hours"] ** 2

# Split the data into features and target variable
X = df.drop(["Performance Index", "Performance Class", "Sleep Hours"], axis=1)
y = df["Performance Class"]

# creating pipelines
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

pipeline = make_pipeline(StandardScaler(), LogisticRegression())

scores = cross_val_score(pipeline, X, y, cv=5)

print("Cross-validation scores:", scores)
print("Mean CV accuracy:", scores.mean())

Cross-validation scores: [0.9715 0.9705 0.979  0.9775 0.9755]
Mean CV accuracy: 0.9748000000000001
